# SimpleStaffChat2 by RefracDevelopment
#--------------------------------------
# Placeholders:
# %player% - Get the player name
# %displayname% - Get the player display name
# %server% - Get the player server
# %message% - Get the message
# %arrow% - Get an arrow for a message
# %arrow_2% - Get alt arrow for a message
# %star% - Get a star for a message
# %circle% - Get a circle for a message
# %empty% - Disable any message with this placeholder
#--------------------------------------
# Used to send messages to staffchat without the
# need to type in /staffchat <message> or /staffchattoggle
# this uses the same format as /staffchat <message>
staffchat-symbol: "@"
adminchat-symbol: "#"
devchat-symbol: "%"
# Change to true if you have LuckPerms installed
luckperms: false
# Change to false if you want to disable all chat symbols
symbols: true

format:
  # Minecraft format
  minecraft-format: "%prefix% &e(%server%) &6&l%player%&7: &f%message%"
  # Format for messages sent by the console.
  console-staffchat-format: "%prefix% &6&lConsole&7: &f%message%"
  # AdminChat format
  adminchat-format: "&8[&4&lAdminChat&8] &e(%server%) &6&l%player%&7: &f%message%"
  # Format for messages sent by the console.
  console-adminchat-format: "&8[&4&lAdminChat&8] &6&lConsole&7: &f%message%"
  # DevChat format
  devchat-format: "&8[&b&lDevChat&8] &e(%server%) &6&l%player%&7: &f%message%"
  # Format for messages sent by the console.
  console-devchat-format: "&8[&b&lDevChat&8] &6&lConsole&7: &f%message%"

# This is for staff joins only
# permissions: simplestaffchat.join, simplestaffchat.switch, simplestaffchat.quit
join:
  enabled: false
  join-format: "&8[&a+&8] &9%player% &fjoined &e%server%&f."
  switch-format: "&8[&b+&8] &9%player% &fswitched server &7(&e%from% &f%arrow% &e%server%&7)&f."
  quit-format: "&8[&c-&8] &9%player% &fleft &e%server%&f."

messages:
  # Used for the %prefix% placeholder in messages
  prefix: "&8[&c&lStaffChat&8]"
  no-permission: "&cYou don't have permission to execute this command."
  reload: "&7Config files reloaded. Changes should be live in-game."
  toggle-on: "%prefix% &7StaffChat toggled &aon&7."
  toggle-off: "%prefix% &7StaffChat toggled &coff&7."
  adminchat-toggle-on: "&8[&4&lAdminChat&8] &7AdminChat toggled &aon&7."
  adminchat-toggle-off: "&8[&4&lAdminChat&8] &7AdminChat toggled &coff&7."
  devchat-toggle-on: "&8[&d&lDevChat&8] &7DevChat toggled &aon&7."
  devchat-toggle-off: "&8[&d&lDevChat&8] &7DevChat toggled &coff&7."
  allchat-toggle-on: "&eAll chat toggled &aon&e."
  staffchat-muted-on: "&eYour StaffChat has been muted."
  staffchat-muted-off: "&eYour StaffChat has been un-muted."
  adminchat-muted-on: "&eYour AdminChat has been muted."
  adminchat-muted-off: "&eYour AdminChat has been un-muted."
  devchat-muted-on: "&eYour DevChat has been muted."
  devchat-muted-off: "&eYour DevChat has been un-muted."
  # If this is set to "custom" you can change the /sc output message to anything
  # If this is set to "toggle" you can use /sc to toggle into staffchat easier
  staffchat-output: "default"
  # staffchat-output must be set to "custom" in order for this to work
  staffchat-message:
    - ""
    - "&c&lSimpleStaffChat2 %arrow2% Help"
    - ""
    - "&c/staffchat <message> - Send staffchat messages."
    - "&c/adminchat <message> - Send adminchat messages."
    - "&c/devchat <message> - Send devchat messages."
    - "&c/staffchattoggle - Send staffchat messages without needing to type a command."
    - "&c/adminchattoggle - Send adminchat messages without needing to type a command."
    - "&c/devchattoggle - Send devchat messages without needing to type a command."
    - "&c/staffchatreload - Reload the config file."
    - ""