#   ___________                __           _________ __           _____  ______________  /\             __
#  /   _____/__| _____ ______ |  |   ____  /   _____//  |______  _/ ____\/ ____\_   ___ \|  |__ _____  _/  |_
#  \_____  \|  |/     \\____ \|  | _/ __ \ \_____  \\   __\__  \ \   __\\   __\/    \  \/|  |  \\__  \ \   __\
#  /        \  |  | |  \  |_\ \  |__  ___/_/        \|  |  / __ \_|  |   |  |  \     \____      \/ __ \_|  |
# /_______  /__|__|_|  /   ___/____/\___  /_______  /|__| (____  /|_ |   |_ |   \______  /___|  /____  /|__|
#         \/         \/|__|             \/        \/           \/   \/     \/          \/     \/     \/

# This is used for automatic file updating purposes
config-version: 2

# The locale to use in the /locale folder
locale: en_US

# Used to send messages to staffchat without the
# need to type in /staffchat <message> or /staffchattoggle
# this uses the same format as /staffchat <message>
symbols:
  # Change to false if you want to disable all chat symbols
  enabled: true
  staffchat-symbol: "@"
  adminchat-symbol: "#"
  devchat-symbol: "%"

format:
  # Minecraft format
  minecraft-format: "%prefix% &e(%server%) &6&l%player%&7: &f%message%"
  # Format for messages sent by the console.
  console-staffchat-format: "%prefix% &6&lConsole&7: &f%message%"
  # AdminChat format
  adminchat-format: "&8[&4&lAdminChat&8] &e(%server%) &6&l%player%&7: &f%message%"
  # Format for messages sent by the console.
  console-adminchat-format: "&8[&4&lAdminChat&8] &6&lConsole&7: &f%message%"
  # DevChat format
  devchat-format: "&8[&b&lDevChat&8] &e(%server%) &6&l%player%&7: &f%message%"
  # Format for messages sent by the console.
  console-devchat-format: "&8[&b&lDevChat&8] &6&lConsole&7: &f%message%"

# This is for staff joins only
# permissions: simplestaffchat.join, simplestaffchat.switch, simplestaffchat.quit
join:
  enabled: false
  join-format: "&8[&a+&8] &9%player% &fjoined &e%server%&f."
  switch-format: "&8[&b+&8] &9%player% &fswitched server &7(&e%from% &f%arrow% &e%server%&7)&f."
  quit-format: "&8[&c-&8] &9%player% &fleft &e%server%&f."

# If this is set to "toggle" you can use /sc to toggle into staffchat easier
staffchat-output: "default"
# staffchat-output must be set to "custom" in order for this to work
staffchat-message:
  - ""
  - "&c&lSimpleStaffChat2 %arrow2% Help"
  - ""
  - "&d/staffchat <message> &7- Send staffchat messages."
  - "&d/adminchat <message> &7- Send adminchat messages."
  - "&d/devchat <message> &7- Send devchat messages."
  - "&d/staffchattoggle &7- Send staffchat messages without needing to type a command."
  - "&d/adminchattoggle &7- Send adminchat messages without needing to type a command."
  - "&d/devchattoggle &7- Send devchat messages without needing to type a command."
  - "&d/staffchathide &7- Allows you to hide staffchat messages."
  - "&d/adminchathide &7- Allows you to hide adminchat messages."
  - "&d/devchathide &7- Allows you to hide devchat messages."
  - "&d/staffchatreload &7- Reload the config file."
  - ""