name: SimpleStaffChat2
version: '${project.version}'
main: me.refracdevelopment.simplestaffchat.spigot.SimpleStaffChat
author: RefracDevelopment
api-version: "1.13"
softdepend:
  - PlaceholderAPI
  - AntiPopup
description: A Simple StaffChat Plugin
website: https://discord.gg/EFeSKPg739
folia-supported: true