#   ___________                __           _________ __           _____  ______________  /\             __
#  /   _____/__| _____ ______ |  |   ____  /   _____//  |______  _/ ____\/ ____\_   ___ \|  |__ _____  _/  |_
#  \_____  \|  |/     \\____ \|  | _/ __ \ \_____  \\   __\__  \ \   __\\   __\/    \  \/|  |  \\__  \ \   __\
#  /        \  |  | |  \  |_\ \  |__  ___/_/        \|  |  / __ \_|  |   |  |  \     \____      \/ __ \_|  |
# /_______  /__|__|_|  /   ___/____/\___  /_______  /|__| (____  /|_ |   |_ |   \______  /___|  /____  /|__|
#         \/         \/|__|             \/        \/           \/   \/     \/          \/     \/     \/

# This is used for automatic file updating purposes
config-version: '3'

symbols:
  # Change to false if you want to disable all chat symbols
  enabled: true
  # Used to send messages to staffchat without the
  # need to type in /staffchat <message> or /staffchattoggle
  # this uses the same format as /staffchat <message>
  staffchat-symbol: "@"
  adminchat-symbol: "#"
  devchat-symbol: "%"

format:
  # Minecraft format
  minecraft-format: "%prefix% <yellow>(%server%) <gold><bold>%player%<gray>: <white>%message%"
  # Format for messages sent by the console.
  console-staffchat-format: "%prefix% <gold><bold>Console<gray>: <white>%message%"
  # AdminChat format
  adminchat-format: "<dark_gray>[<dark_red><bold>AdminChat<dark_gray>] <yellow>(%server%) <gold><bold>%player%<gray>: <white>%message%"
  # Format for messages sent by the console.
  console-adminchat-format: "<dark_gray>[<dark_red><bold>AdminChat<dark_gray>] <gold><bold>Console<gray>: <white>%message%"
  # DevChat format
  devchat-format: "<dark_gray>[<aqua><bold>DevChat<dark_gray>] <yellow>(%server%) <gold><bold>%player%<gray>: <white>%message%"
  # Format for messages sent by the console.
  console-devchat-format: "<dark_gray>[<aqua><bold>DevChat<dark_gray>] <gold><bold>Console<gray>: <white>%message%"

# This is for staff joins only
# permissions: simplestaffchat.join, simplestaffchat.switch, simplestaffchat.quit
join:
  enabled: false
  join-format: "<dark_gray>[<aqua>+<dark_gray>] <blue>%player% <white>joined <yellow>%server%<white>."
  switch-format: "<dark_gray>[<aqua>+<dark_gray>] <blue>%player% <white>switched server <gray>(<yellow>%from% <white>%arrow% <yellow>%server%<gray>)<white>."
  quit-format: "<dark_gray>[<red>-<dark_gray>] <blue>%player% <white>left <yellow>%server%<white>."

messages:
  # Used for the %prefix% placeholder in messages
  prefix: "<dark_gray>[<red><bold>StaffChat<dark_gray>]"
  no-permission: "<red>You don't have permission to execute this command."
  reload: "<gray>Config files reloaded. Changes should be live in-game."
  staffchat-toggle-on: "%prefix% <yellow>StaffChat toggled <green>on<yellow>."
  staffchat-toggle-off: "%prefix% <yellow>StaffChat toggled <red>off<yellow>."
  adminchat-toggle-on: "<dark_gray>[<red><bold>AdminChat<dark_gray>] <yellow>AdminChat toggled <green>on<yellow>."
  adminchat-toggle-off: "<dark_gray>[<red><bold>AdminChat<dark_gray>] <yellow>AdminChat toggled <red>off<yellow>."
  devchat-toggle-on: "<dark_gray>[<aqua><bold>DevChat<dark_gray>] <yellow>DevChat toggled <green>on<yellow>."
  devchat-toggle-off: "<dark_gray>[<aqua><bold>DevChat<dark_gray>] <yellow>DevChat toggled <red>off<yellow>."
  allchat-toggle-on: "<yellow>All chat toggled <green>on<yellow>."
  staffchat-muted-on: "<yellow>Your StaffChat has been muted."
  staffchat-muted-off: "<yellow>Your StaffChat has been un-muted."
  adminchat-muted-on: "<yellow>Your AdminChat has been muted."
  adminchat-muted-off: "<yellow>Your AdminChat has been un-muted."
  devchat-muted-on: "<yellow>Your DevChat has been muted."
  devchat-muted-off: "<yellow>Your DevChat has been un-muted."
  # If this is set to "toggle" you can use /sc to toggle into staffchat easier
  staffchat-output: "default"
  staffchat-message:
    - ""
    - "<red><bold>SimpleStaffChat2 %arrow2% Help"
    - ""
    - "<red>/staffchat <message> <gray>- Send staffchat messages."
    - "<red>/adminchat <message> <gray>- Send adminchat messages."
    - "<red>/devchat <message> <gray>- Send devchat messages."
    - "<red>/staffchattoggle <gray>- Send staffchat messages without needing to type a command."
    - "<red>/adminchattoggle <gray>- Send adminchat messages without needing to type a command."
    - "<red>/devchattoggle <gray>- Send devchat messages without needing to type a command."
    - "<red>/staffchatreload <gray>- Reload the config file."
    - ""