#   ___________                __           _________ __           _____  ______________  /\             __
#  /   _____/__| _____ ______ |  |   ____  /   _____//  |______  _/ ____\/ ____\_   ___ \|  |__ _____  _/  |_
#  \_____  \|  |/     \\____ \|  | _/ __ \ \_____  \\   __\__  \ \   __\\   __\/    \  \/|  |  \\__  \ \   __\
#  /        \  |  | |  \  |_\ \  |__  ___/_/        \|  |  / __ \_|  |   |  |  \     \____      \/ __ \_|  |
# /_______  /__|__|_|  /   ___/____/\___  /_______  /|__| (____  /|_ |   |_ |   \______  /___|  /____  /|__|
#         \/         \/|__|             \/        \/           \/   \/     \/          \/     \/     \/

# This is used for automatic file updating purposes
config-version: '3'

# The locale to use in the /locale folder
locale: en_US

# This is so stuff like Discord can get the server name
# Placeholder: %server%
server-name: hub

# These settings will fully disable the chat/feature
# A restart of the server is required
modules:
  staffchat: true
  adminchat: true
  devchat: true
  # This is for discord webhook messages
  discord: false
  # This is for staff join messages
  join: false
  # This is for toggle commands like /sctoggle, /schide and /chat
  chat-toggle: true
  # This is for the symbol chats
  symbols: true