name: Bungee
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Rename JAR with Build Number
      run: |
        original_jar=$(find SimpleStaffChat-Bungee/target/ -type f -name "SimpleStaffChat-Bungee-*.jar")
        new_name=$(echo "$original_jar" | sed "s/SimpleStaffChat-Bungee-\(.*\)\.jar/SimpleStaffChat-Bungee-\1+${{ github.run_number }}.jar/")
        mv "$original_jar" "$new_name"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3 # https://github.com/actions/upload-artifact/releases
      with:
        name: Click here to download
        path: target/SimpleStaffChat-Bungee-*+${{ github.run_number }}.jar
