name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Project
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B install --file ./SimpleStaffChat-Spigot/pom.xml
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'Spigot-${{ env.PROJECT_VERSION }}'
          release_name: SimpleStaffChat-Spigot ${{ env.PROJECT_VERSION }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './SimpleStaffChat-Spigot/target/SimpleStaffChat-Spigot-${{ env.PROJECT_VERSION }}.jar'
          asset_name: 'SimpleStaffChat-Spigot-${{ env.PROJECT_VERSION }}.jar'
          asset_content_type: 'application/java-archive'
